//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorONG.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class entradasSalidasInformacion
    {
        public int id { get; set; }
        public int tipoDocumento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string emisor { get; set; }
        public int numDocumentos { get; set; }
        public int tipoDatos { get; set; }
        public int formaEnvio { get; set; }
        public int personaResponsable { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual formasEnvio formasEnvio { get; set; }
        public virtual tipoDocumento tipoDocumento1 { get; set; }
        public virtual tiposDatos tiposDatos { get; set; }
    }
}
