//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorONG.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestor_ongd_sps_prodEntities : DbContext
    {
        public gestor_ongd_sps_prodEntities()
            : base("name=gestor_ongd_sps_prodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<perfiles> perfiles { get; set; }
        public virtual DbSet<personas> personas { get; set; }
        public virtual DbSet<personas_perfiles> personas_perfiles { get; set; }
        public virtual DbSet<sede_delegacion> sede_delegacion { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<voluntario> voluntario { get; set; }
    }
}
