//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorONG.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class incidenciasSeguridad
    {
        public int id { get; set; }
        public System.DateTime fechaIncidencia { get; set; }
        public int idTipoIncidencia { get; set; }
        public string descripcion { get; set; }
        public string efectosDerivados { get; set; }
        public string medidasCorrectoras { get; set; }
        public int idComunicante { get; set; }
        public int idReceptor { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual empleados empleados1 { get; set; }
        public virtual tiposIncidencias tiposIncidencias { get; set; }
    }
}
