//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorONG.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class voluntarios : personas
    {
        public System.DateTime fechaAlta { get; set; }
        public Nullable<int> sede { get; set; }
    
        public virtual sede_delegacion sede_delegacion { get; set; }
    }
}
